export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const AUTH_ERROR = 'AUTH_ERROR'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

export const GET_PROFILE = 'GET_PROFILE'
export const ERROR_PROFILE = 'ERROR_PROFILE'

export const INPUT_SUCCESS = 'INPUT_SUCCESS'
export const INPUT_FAIL = 'INPUT_FAIL'

export const PANTRY_SUCCESS = 'PANTRY_SUCCESS'
export const PANTRY_UPDATE = 'PANTRY_UPDATE'
export const PANTRY_FAIL = 'PANTRY_FAIL'

export const INGREDIENTS_SUCCESS = 'INGREDIENTS_SUCCESS'
export const INGREDIENTS_UPDATE = 'INGREDIENTS_UPDATE'
export const INGREDIENTS_DELETE = 'INGREDIENTS_DELETE'
export const INGREDIENTS_FAIL = 'INGREDIENTS_FAIL'

export const RECIPES_SUCCESS = 'RECIPES_SUCCESS'
export const RECIPES_UPDATE = 'RECIPES_UPDATE'
export const RECIPES_FAIL = 'RECIPES_FAIL'

export const PLANNER_SUCCESS = 'PLANNER_SUCCESS'
export const PLANNER_FAIL = 'PLANNER_FAIL'

export const GARMIN_LOGIN = 'GARMIN_LOGIN'
export const GARMIN_LOGIN_FAIL = 'GARMIN_LOGIN_FAIL'

export const ACTIVITY_SUCCESS = 'ACTIVITY_SUCCESS'
export const ACTIVITY_FAIL = 'ACTIVITY_FAIL'

export const CLEAR_USER = 'CLEAR_USER'
export const LOAD_USER = 'LOAD_USER'
export const FAIL_USER = 'FAIL_USER'

export const LOADING = 'LOADING'
